/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkRouteImport } from './routes/work'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardClaimRouteImport } from './routes/dashboard.claim'
import { Route as DashboardElectionsRouteImport } from './routes/dashboard.elections'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardPayrollRouteImport } from './routes/dashboard.payroll'
import { Route as DashboardStakingRouteImport } from './routes/dashboard.staking'
import { Route as DashboardUniverseRouteImport } from './routes/dashboard.universe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimRoute = DashboardClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardElectionsRoute = DashboardElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayrollRoute = DashboardPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStakingRoute = DashboardStakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUniverseRoute = DashboardUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/work': typeof WorkRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/elections': typeof DashboardElectionsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/staking': typeof DashboardStakingRoute
  '/dashboard/universe': typeof DashboardUniverseRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/work': typeof WorkRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/elections': typeof DashboardElectionsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/staking': typeof DashboardStakingRoute
  '/dashboard/universe': typeof DashboardUniverseRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/work': typeof WorkRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/elections': typeof DashboardElectionsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/staking': typeof DashboardStakingRoute
  '/dashboard/universe': typeof DashboardUniverseRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/pricing'
    | '/services'
    | '/team'
    | '/work'
    | '/dashboard/claim'
    | '/dashboard/elections'
    | '/dashboard/invoices'
    | '/dashboard/payments'
    | '/dashboard/payroll'
    | '/dashboard/staking'
    | '/dashboard/universe'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/pricing'
    | '/services'
    | '/team'
    | '/work'
    | '/dashboard/claim'
    | '/dashboard/elections'
    | '/dashboard/invoices'
    | '/dashboard/payments'
    | '/dashboard/payroll'
    | '/dashboard/staking'
    | '/dashboard/universe'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/pricing'
    | '/services'
    | '/team'
    | '/work'
    | '/dashboard/claim'
    | '/dashboard/elections'
    | '/dashboard/invoices'
    | '/dashboard/payments'
    | '/dashboard/payroll'
    | '/dashboard/staking'
    | '/dashboard/universe'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claim': {
      id: '/dashboard/claim'
      path: '/claim'
      fullPath: '/dashboard/claim'
      preLoaderRoute: typeof DashboardClaimRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/elections': {
      id: '/dashboard/elections'
      path: '/elections'
      fullPath: '/dashboard/elections'
      preLoaderRoute: typeof DashboardElectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payroll': {
      id: '/dashboard/payroll'
      path: '/payroll'
      fullPath: '/dashboard/payroll'
      preLoaderRoute: typeof DashboardPayrollRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staking': {
      id: '/dashboard/staking'
      path: '/staking'
      fullPath: '/dashboard/staking'
      preLoaderRoute: typeof DashboardStakingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/universe': {
      id: '/dashboard/universe'
      path: '/universe'
      fullPath: '/dashboard/universe'
      preLoaderRoute: typeof DashboardUniverseRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClaimRoute: typeof DashboardClaimRoute
  DashboardElectionsRoute: typeof DashboardElectionsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPayrollRoute: typeof DashboardPayrollRoute
  DashboardStakingRoute: typeof DashboardStakingRoute
  DashboardUniverseRoute: typeof DashboardUniverseRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClaimRoute: DashboardClaimRoute,
  DashboardElectionsRoute: DashboardElectionsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPayrollRoute: DashboardPayrollRoute,
  DashboardStakingRoute: DashboardStakingRoute,
  DashboardUniverseRoute: DashboardUniverseRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
